FROM node:14

WORKDIR /app

RUN npm install -g truffle ganache-cli

COPY . .

RUN npm install

RUN truffle compile

EXPOSE 8545

CMD ganache-cli -d -m "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" & \
    sleep 5 && \
    truffle migrate --network development && \
    tail -f /dev/null
